### ISSUE TITLE
Support for new versions of Windows SDKs in Source Link Inserter

### ISSUE THREAD

**Issue by MichaelKetting** [re-motion/BuildTools#3]
Registry HKLM\SOFTWARE\Microsoft\Windows Kits\Installed Roots contains values for the kits root:
- KitsRoot
- KitsRoot81
- KitsRoot10
  etc
  Problem 1: presently, only KitsRoot is supported.
  Problem 2: future versions will add keys with an unknown name. It's probably best to always tray and use a known name, but what if the tool is too old? It could be updated or it could try to discover the next installed version. Here, care must be taken to use a sensible ordering. When adding special handling for KitsRoot and KitsRoot81, the remaining folders can likely be sorted alphabetically since Windows 10 kits start with KitsRoot10 and will probably go from there until the counter gets 3 digits in the distant future. We will likely not reach this point before we need more than 640kB of RAM ;) Also check for older version (v6) of the Windows SDK, so we can de-prioritize a KitsRoot61 (in case something like this exists).

**Comment by fschmied** [comment]
@MichaelKetting Has this already been implemented? https://github.com/re-motion/BuildTools/blob/master/MSBuildTasks/InsertSourceLinks.cs#L60 seems to be searching for the newest KitsRoot* (FileVersion, not alphabetically).

**Comment by fschmied** [comment]
Related: https://github.com/GitTools/GitLink/issues/40

**Comment by MichaelKetting** [comment]
Fixed with v1.0.6180.28602
(https://www.myget.org/feed/re-motion-infrastructure/package/nuget/Remotion.BuildTools.MSBuildTasks/1.0.6180.28602)

@fschmied The sort by file version is by design, since that's the only sensible way to get the latest installed version.

@fschmied The re-distributable pdbstr.exe sounds interesting. Unfortunately, I couldn't find an official source for the redistribution license.
